### PR TITLE
Update for beta8

### PR DESCRIPTION
**Pull request by matteocontrini**
Here's a PR for beta8 support. I tested the features and everything seems to work.

The only thing I don't understand is why when enabling the extension the settings modal is not shown. What I see is that the page becomes "darker", as if the modal was open but invisibile. Clicking anywhere closes the invisibile modal, and then the modal can be opened manually by clicking the "Settings" menu item.

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
Sorry I didn't notice your PR (because I had notifications disabled :see_no_evil: ), I'll try to take a look soon.

I will check with the other FriendsOfFlarum members what we want to do with this extension. Either way, it will have to switch namespace if it's updated.

**Comment by Ralkage** [comment]
I ended up doing this from scratch to update for Beta 9 instead, thank you for your contribution and time @matteocontrini! :)

**Comment by matteocontrini** [comment]
Thanks!

**Comment by matteocontrini** [comment]
@Ralkage is the release on Packagist for `fof/amazon-affiliation` correct? I installed it but I'm seeing the old name...

immagine

And when I enable it there's no settings button.

**Comment by Ralkage** [comment]
@matteocontrini I haven't release the updated version yet which includes my recent commits :) it will be out tomorrow as well as a new discussion on Flarum Discuss👍

**Pull request closed without merging**
